# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba4414d6df9bdeb877e1c973d938a20d1890fd8c96c49938215ab51f59f126c01c3ccf64edc9b98fb3a5b27ebf4f7de380793b7de5d5dedbb1ad59a77694e257

test:
  secret_key_base: c01638394c277dc4f544132910bf445dec52a816b94f8a4dd41cdef2e98129ba597dbd39cfef35cf2836b467410f154aecd3c4431b3a68135f603b072552abf8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
